main.py
from flask import Flask, request, render_template

from views.items import items_app
from views.products import products_app


app = Flask(__name__)
app.register_blueprint(items_app)
app.register_blueprint(products_app)


@app.get("/")
def index_view():
    # return "<h1>Hello Index!!</h1>"
    features = ["Items", "Products (WIP)", "Hello views"]
    return render_template("index.html", features=features)


def print_request_info():
    print(request)


# @app.get("/hello-plain/")
# def hello_plain_view():
#     name = "World!"
#     return f"Hello {name}"


@app.get("/hello-plain/")
@app.get("/hello/")
def hello_view():
    name = request.args.get("name", "")
    name = name.strip()
    if not name:
        name = "World"

    # return f"<h1>Hello {name}!</h1>"
    return render_template("hello.html", name=name)


@app.get("/images/")
@app.get("/images/<path:img_dir>/")
def get_image(img_dir: str = "default/images/path"):
    return {
        "data": {
            "image": "todo load",
            "path": img_dir,
        },
    }


if __name__ == "__main__":
    app.run(
        debug=True,
    )

views/items.py
from flask import Blueprint

items_app = Blueprint(
    "items_app",
    __name__,
    url_prefix="/items",
)


@items_app.get("/")
def get_items_list():
    return {
        "data": [
            {
                "id": 1,
                "name": "I1",
            },
            {
                "id": 2,
                "name": "I2",
            },
        ],
    }


# @items_app.get("/<int:item_id>/")
# def get_item_by_id_int(item_id: int):
#     return {
#         "data": {
#             "id": item_id,
#             "name": f"I{item_id}",
#             "comment": "integer id",
#         },
#     }


@items_app.get("/<int:item_id>/")
@items_app.get("/<string:item_id>/")
def get_item_by_id_str(item_id: str):
    return {
        "data": {
            # "id": item_id.upper(),
            "id": item_id,
            "name": f"I{item_id}",
            "comment": "some id",
            "type": str(type(item_id)),
        },
    }

views/products.py
from dataclasses import dataclass

from flask import Blueprint, render_template, request, redirect, url_for
from werkzeug.exceptions import BadRequest, NotFound


products_app = Blueprint(
    "products_app",
    __name__,
    url_prefix="/products",
)


@dataclass(frozen=True, slots=True)
class Product:
    id: int
    name: str


@dataclass(frozen=False, slots=True)
class ProductsStorage:
    products: dict[int, Product]
    last_index: int = 0

    @property
    def next_index(self):
        self.last_index += 1
        return self.last_index

    def create(self, name: str) -> Product:
        product = Product(id=self.next_index, name=name)
        self.products[product.id] = product
        return product


storage = ProductsStorage(products={})
storage.create("Laptop")
storage.create("Desktop")
storage.create("Smartphone")


@products_app.get("/", endpoint="list")
def get_products():
    products = list(storage.products.values())
    return render_template("products/list.html", products=products)


@products_app.get("/<int:product_id>/", endpoint="details")
def get_product_details(product_id: int):
    # try:
    #     product = storage.products[product_id]
    # except KeyError:
    #     ...
    product = storage.products.get(product_id)
    if product is None:
        raise NotFound(f"Product #{product_id} not found!")

    return render_template("products/details.html", product=product)


@products_app.route("/create/", methods=["GET", "POST"], endpoint="create")
def create_product():
    if request.method == "GET":
        return render_template("products/create.html")

    product_name = request.form.get("product-name", "")
    product_name = product_name.strip()
    if not product_name:
        raise BadRequest("Field product-name is required!")

    product = storage.create(product_name)
    url = url_for("products_app.details", product_id=product.id)
    return redirect(url)

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <style>
    body {
      background-color: #f7f7f7;
    }
  </style>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}
    Base Title
  {% endblock %}</title>
</head>
<body>
  {% block top %}
  {% endblock %}
  {% block body %}
    Base body
  {% endblock %}
<footer>
  &copy; OTUS 2023
</footer>
</body>
</html>

templates/hello.html
{% extends 'base.html' %}

{% block title %}
  Hello View
{% endblock %}

{% block body %}
  <h1>Hello {{ name }}!</h1>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
  Index page
{% endblock %}

{% block body %}
  <h1>Hello Index!</h1>
  <div>
    <ul>
      {% for name in ['Bob', 'Alice', 'Jim'] %}
        <li>{{ name }}</li>
      {% endfor %}
    </ul>
  </div>
  <div>
    <ul>
      {% for feature in features %}
        <li>{{ feature }}</li>
      {% endfor %}
    </ul>
  </div>

  <div>
    <p>Links:</p>
    <ul>
      <li>
        <a href="{{ url_for('products_app.list') }}">
          Products
        </a>
      </li>
    </ul>
  </div>
{% endblock %}

templates/products/create.html
{% extends 'products/products-base.html' %}

{% block title %}
  Create Product
{% endblock %}

{% block body %}
  <h2>Product details:</h2>

  <form method="post">
    <label for="product-name-id">Product name</label>
    <input id="product-name-id" type="text" name="product-name" required>

    <button type="submit">Create</button>
  </form>

  <div>
    <a href="{{ url_for('products_app.list') }}">
      Back to products list
    </a>
  </div>
{% endblock %}

templates/products/details.html
{% extends 'products/products-base.html' %}

{% block title %}
  Product #{{ product.id }} Detail
{% endblock %}

{% block body %}
  <h2>Product #{{ product.id }} Detail</h2>
  <h3>Name: {{ product.name }}</h3>

  <div>
    <a href="{{ url_for('products_app.list') }}">
      Back to products list
    </a>
  </div>
{% endblock %}

templates/products/list.html
{% extends 'products/products-base.html' %}

{% block title %}
  Products list
{% endblock %}

{% block body %}
  <h2>Products:</h2>

  <div>
    <ul>
      {% for product in products %}
        <li>
          <a href="{{ url_for('products_app.details', product_id=product.id) }}">
            {{ product.name }}
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>

  <div>
    <a href="{{ url_for('products_app.create') }}">Create a new product</a>
  </div>

{% endblock %}

templates/products/products-base.html
{% extends 'base.html' %}

{% block top %}
{#  <h1>Products</h1>#}
<!-- my comment -->
{% endblock %}